### ISSUE TITLE
Gateway crashes Node red

### ISSUE THREAD

**Issue by Elcondor32** [bmdevx/node-red-contrib-ecowitt-gateway#2]
My weather station : https://www.foshk.com/wifi_weather_station/wh2650.html

First of all, the Gateway is great and works properly with only one inhouse sensor for temperture, pressure and humidity.

Looks in node red : ![grafik](https://github.com/user-attachments/assets/45ca3fd9-af36-40cb-a343-daa11f34a377)

After activating the outside station for outside temperature and humidity , wind speed and direction, rain, etc. 
Node red crashes at every timer trigger which triggers the ecowitt Gateway. 
See here the system messages on Raspberry debian system (17:37:00 and 17:38:29) : 
![grafik](https://github.com/user-attachments/assets/24982657-4af3-4194-b97f-1d90dcf4b3cb)

When I deactivate the outside station in wheater stations App the inner station works proper without any problem.

Can you help ?

**Comment by bmdevx** [comment]
I think I have found the issue in the code, but before I implement it would like to check to see if this solves your issue. In the Live Data node if you turn off "Include Rain Data" does it prevent a crash. That particular setting mostly applies to the new piezo electric sensors and rain data should still be included from your current outdoor setup though it may be having an issue with the older gw100 gateways. If that does not work please run the following code in a nodejs instance. I can use the data to debug and verify the fix.

```js
const EWG = require('ecowitt-gateway');
const gw = EWG('REPLACE with IPADDRESS of GATEWAY');

gw.runCommand(0x27)
	.then(buffer => {
         console.log(`CMD_LD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x34)
	.then(buffer => {
         console.log(`CMD_R_RD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x57)
	.then(buffer => {
         console.log(`CMD_R_R: ${buffer.toString('hex').toUpperCase()}\n`);
     });
```

**Comment by Elcondor32** [comment]
Hi Bryan,

this evening I have checked what you said. With or Without "Include Rain Data" makes no difference ! Node Red crashes when trigger Ecowitt Gateway.

I tried to run the code you send me, but I'm a absolute Node Red and Java beginner! I don't know what you mean with "run it in a nodejs instance" Do you mean in a Function node ?
I tried this but no success. I understud that I have to put in the IP adress of weather station  (192.168.178.46) in line 2. Do I have to change something in line 1 ?
I need a bit help, thank you in advance.
Maybe a ready test flow ? Together we can find the problem !

Eberhard

**Comment by Elcondor32** [comment]
Hi Bryan,
today I could manage to run your small program to get the informations you are asking for.

Please see the result here below 👍 

const EWG = require('ecowitt-gateway');
const gw = new EWG('192.168.178.46');

gw.runCommand(0x27)
        .then(buffer => {
         console.log(`CMD_LD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x34)
        .then(buffer => {
         console.log(`CMD_R_RD: ${buffer.toString('hex').toUpperCase()}\n`);
     });

gw.runCommand(0x57)
        .then(buffer => {
         console.log(`CMD_R_R: ${buffer.toString('hex').toUpperCase()}\n`);
     });

Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 69,
  [Symbol(trigger_async_id_symbol)]: 64
}
> CMD_LD: FFFF27004001012306250826440929A802002F075C0A00430B00000C00001500000000160000170019000F0E0000100000110000120000001913000000190D0000F8

CMD_R_RD: FFFF341700000000000000000000000000000019000000197D

CMD_R_R: FFFF5700290E000010000000001100000000120000001913000000190D00000F0064880000017A017B0005

I hope this will help you to find the problem.

Eberhard

**Comment by bmdevx** [comment]
I think I have fixed the issue in version 1.0.9. It looks like your ReadRain command is returning data formatted differently than expected compared to my GW2000 gateway. I have put in a check in the node to automatically run the best command given the gateway device. If it is still failing please try changing the Rain Method setting in the config node to ReadReadData instead of Auto. If that still does not work, please rerun the code above including the following.

```js
gw.runCommand(0x50)
.then(buffer => {
console.log(CMD_FIRMWARE: ${buffer.toString()}\n);
console.log(CMD_FIRMWARE_RAW: ${buffer.toString('hex').toUpperCase()}\n);
});

gw.runCommand(0x30)
.then(buffer => {
console.log(CMD_SETTINGS: ${buffer.toString('hex').toUpperCase()}\n);
});

gw.getSensors()
.then(buffer => {
console.log('Sensors:\n');
console.log(JSON.stringify(buffer.toString(), null, 1));
});
```

**Comment by Elcondor32** [comment]
Hi Bryan,
I tested it in Node Red. But no success.
With "deploy" I got this message 

13.11.2024, 20:15:27[node: test_Eco](http://192.168.178.45:1880/#)msg : error
"TypeError: Cannot read properties of undefined (reading 'toLowerCase')"
13.11.2024, 20:15:27[node: 93a8db6914bad36f](http://192.168.178.45:1880/#)
msg : error
"TypeError: Cannot read properties of null (reading 'gateway')"

Thats it, no more reaction with inject trigger !

**Comment by bmdevx** [comment]
In the config node, what is the rainMethod set to? I have also just pushed 1.0.10 that should fix the issue above.

**Comment by Elcondor32** [comment]
Hi Bryan,
the new version of the ecowitt node works now perfect. See below.

![grafik](https://github.com/user-attachments/assets/2d40488b-e9fc-4534-a3f1-a21ce8261fac)

Thank you very much
Eberhard
